/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IDog } from "./store/AppState";
export { IDog } from "./store/AppState";
export namespace Components {
    interface AppDog {
        "closeDialog": () => Promise<void>;
        "dog": IDog;
        "openDialog": () => Promise<void>;
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppDogElement extends Components.AppDog, HTMLStencilElement {
    }
    var HTMLAppDogElement: {
        prototype: HTMLAppDogElement;
        new (): HTMLAppDogElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-dog": HTMLAppDogElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppDog {
        "dog"?: IDog;
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-dog": AppDog;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dog": LocalJSX.AppDog & JSXBase.HTMLAttributes<HTMLAppDogElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
